services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: .
          target: /app
          action: sync
    container_name: learning_python_basics
    # command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      # - 80:80
      # - 5678:5678
      - 3000:3000    
    volumes:
      - ./code:/app/code  # Sync local "code" folder with /app in the container
    # depends_on:
    #   - redis
    working_dir: /app
    stdin_open: true  # Keep the container open for interactive use
    tty: true

  # redis:
  #   image: redis:alpine
  
volumes:
  learning:      # Bind the named volume to /app